### ISSUE TITLE
Cannot load datasets if JWT is expired

### ISSUE THREAD

**Issue by ddehueck** [cvfadmin/COVE#24]

**Comment by Eric4Jiang** [comment]
@jwt_optional returns error when instead of datasets to display a passed an expired JWT. A solution I found was just to simply remove @jwt_optional since it's not necessary.


Source: https://flask-jwt-extended.readthedocs.io/en/latest/optional_endpoints.html

"If a JWT that is expired or badly constructed is sent in with the request, an error will be returned instead of calling the protected endpoint as if no token was present in the request."

**Comment by Eric4Jiang** [comment]
Solution was to prompt user for relogin when their session expired.
