### ISSUE TITLE
DataTypes tag search does not work.

### ISSUE THREAD

**Issue by Eric4Jiang** [cvfadmin/COVE#50]
Duplicate:
1) Select "Depth" tag in DataTypes.
2) Search results don't have "Depth" Tag.

**Comment by Eric4Jiang** [comment]
I have the fix. Will commit it shortly.

**Comment by Eric4Jiang** [comment]
Problem is that in views/Home.vue, searchTag stores DataTypes tags in "dataTypes". However, when we add a tag, the category is "data_types". 

So the "updateTags()" function is incorrect. @ddehueck Having two different names is confusing. Should we stich with dataTypes, or data_types?

**Comment by ddehueck** [comment]
Could you create a pull request so I could look it over and test it that way?

They're named differently due to different origins. The "data_types" is raw data from the API while dataTypes is a property in vuejs containing tag objects. The vuejs properties could use better names (maybe something indicating they're holding tag objects like "dataTypeTags") but I wouldn't advocate for them being the same name.
