### ISSUE TITLE
Can not display the thumbnail image

### ISSUE THREAD

**Issue by yuliangguo** [cvfadmin/COVE#89]
I just use a .jpg image hosted on github, but wesite can not display it. Is there any guidance on the format of the thumbnail image?

**Comment by craymichael** [comment]
Yes, this is a common issue because the URL is misleading. Images hosted in GitHub repositories need to have links to the actual image content rather than the repository display page. To do so, right click the image, open image (in new tab), then use that URL instead. Let me know if that works for you.

**Comment by yuliangguo** [comment]
thx, using the link from new tab works.
